version: "3"
services:
    python3:
        build: .
        container_name: 'python3'
        stdin_open: true
        tty: true
        environment:
          - DISPLAY=192.168.1.14:0.0

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'gra3'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : <MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted

